---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-2
  namespace: kafka
  labels:
    name: kafka-2
    broker_id: "2"
spec:
  replicas: 1
  selector:
    name: kafka-2
    broker_id: "2"
  template:
    metadata:
      labels:
        name: kafka-2
        broker_id: "2"
        service: kafka
    spec:
      containers:
        - name: kafka
          image: gcr.io/sqhive-backend/kafka:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "2"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-2"
            - name: ZOOKEEPER_CONNECT
              value: "zookeeper-1.zookeeper:2181,zookeeper-2.zookeeper:2181,zookeeper-3.zookeeper:2181"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /data
              name: nfs-kafka-data
      volumes:
        - name: nfs-kafka-data
          persistentVolumeClaim:
            claimName: nfs-kafka-2-data
