apiVersion: v1
kind: Service
metadata:
  name: kafka-burrow
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - name: burrow
      targetPort: 8000
      port: 80
  selector:
    name: kafka-burrow
