apiVersion: v1
kind: Service
metadata:
  name: kafka-rest
  namespace: kafka
spec:
  type: ClusterIP
  clusterIP: 10.91.254.6
  ports:
    - name: rest
      targetPort: 8082
      port: 80
  selector:
    name: kafka-rest
