apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-rest
  namespace: kafka
  labels:
    name: kafka-rest
spec:
  replicas: 1
  selector:
    name: kafka-rest
  template:
    metadata:
      labels:
        name: kafka-rest
    spec:
      containers:
        - name: kafka-rest
          image: confluentinc/cp-kafka-rest:3.3.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "250Mi"
          env:
            - name: KAFKA_REST_ZOOKEEPER_CONNECT
              value: "zookeeper-1.zookeeper:2181,zookeeper-2.zookeeper:2181,zookeeper-3.zookeeper:2181"
            - name: KAFKA_REST_LISTENERS
              value: "http://kafka-rest.kafka"
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: "http://kafka-schema.kafka"
          ports:
            - containerPort: 8082
