apiVersion: v1
kind: Service
metadata:
  name: kafka-schema
  namespace: kafka
spec:
  type: ClusterIP
  clusterIP: 10.91.254.5
  ports:
    - name: schema
      targetPort: 8081
      port: 80
  selector:
    name: kafka-schema
