---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  labels:
    name: kafka-2
    namespace: kafka
    service: kafka
    broker_id: "2"
spec:
  clusterIP: 10.91.254.50
  type: ClusterIP
  ports:
    - name: broker
      port: 9092
  selector:
    name: kafka-2
    broker_id: "2"